name: ind_utils
description: Ind_utils package to simplify use for SizedBox, beautiful Log, creating screen, styles, write assets images file code
license: MIT
maintainer: AdobixTech
homepage: https://indiancreator.in/
repository: https://github.com/adobix/ind_utils
issue_tracker: https://github.com/adobix/ind_utils/issues
version: 2.0.12
funding:
  - https://github.com/ansaralisah

logo: assets/logo.webp

screenshots:
  - description: "Package Ind Utils"
    path: assets/logo.webp

environment:
  sdk: '>=3.0.6 <4.0.0'
  flutter: ">=3.27.1"

dependencies:
  flutter:
    sdk: flutter
  interact: ^2.2.0
  path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

topics:
  - assets
  - screen
  - styles
  - logs
