name: ind_utils
description: 'Ind_utils package to simplify SizedBox and Padding usage, reducing repetitive code.'
version: 1.0.1
homepage: https://github.com/ansaralisahh/ind_utils.git
license: MIT

environment:
  sdk: '>=3.0.6 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  path: ^1.8.0 # For handling paths in your file generation logic

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0 # For linting and code quality checks

executables:
  helper_gen: bin/helper_gen.dart
  assets_gen: bin/assets_gen.dart
  screen_gen: bin/screen_gen.dart
