name: ind_utils
description: Ind_utils package to simplify use for SizedBox, beautiful Log, creating screens, styles, write assets images file code
license: MIT
maintainer: Mrr Hak
homepage: https://indiancreator.in/
repository: https://github.com/adobix/ind_utils
issue_tracker: https://github.com/adobix/ind_utils/issues
version: 1.0.9
funding:
  - https://github.com/ansaralisah

logo: assets/logo.webp

screenshots:
  - description: "Ind Utils"
    path: assets/logo.webp


environment:
  sdk: '>=3.0.6 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  path: ^1.8.0
  interact: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0


topics:
  - assets
  - screens
  - styles
  - logs